export const testBusinesses = [
  {
    id: 1,
    auth0Id: '1',
    name: 'Sharons Hairdressing',
    address: '123 lane rd, Grey Lynn, Auckland',
    category: 'Hairdressers',
    reliabilityScore: 4,
    rating: 80,
    suburb: 'Grey Lynn',
    city: 'Auckland',
  },
  {
    id: 2,
    auth0Id: '2',
    name: 'Petes Hardware',
    address: '70 Hardout st, Grey Lynn, Auckland',
    category: 'Hardware store',
    reliabilityScore: 10,
    rating: 88,
    suburb: 'Grey Lynn',
    city: 'Auckland',
  },
  {
    id: 3,
    auth0Id: '3',
    name: 'Eye Pop',
    address: '4 Vision st, Grey Lynn, Auckland',
    category: 'Optometrist',
    reliabilityScore: 4,
    rating: 90,
    suburb: 'Grey Lynn',
    city: 'Auckland',
  },
  {
    id: 4,
    auth0Id: '4',
    name: 'Coffee Candy',
    address: '10 Espresso st, Grey Lynn, Auckland',
    category: 'Cafe',
    reliabilityScore: 20,
    rating: 98,
    suburb: 'Grey Lynn',
    city: 'Auckland',
  },
  {
    id: 5,
    auth0Id: '5',
    name: 'Delilahs Dentist',
    address: '50 Filling st, Grey Lynn, Auckland',
    category: 'Dentist',
    reliabilityScore: 66,
    rating: 50,
    suburb: 'Grey Lynn',
    city: 'Auckland',
  },
  {
    id: 6,
    auth0Id: '6',
    name: 'Espresso Myself',
    address: '80 Loud st, Grey Lynn, Auckland',
    category: 'Cafe',
    reliabilityScore: 4,
    rating: 67,
    suburb: 'Grey Lynn',
    city: 'Auckland',
  },
]
