/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('Businesses').del()
  await knex('Businesses').insert([
    {
      id: 1,
      auth0_ID: '1',
      name: "Sharon's Hairdressing",
      address: '123 Lane Rd, Grey Lynn, Auckland',
      category: 'Hairdressers',
      reliability_positive: 4,
      reliability_negative: 5,
      rating: 80,
      suburb: 'Grey Lynn',
      city: 'Auckland',
    },
    {
      id: 2,
      auth0_ID: '2',
      name: "Pete's Hardware",
      address: '70 Hardout St, Grey Lynn, Auckland',
      category: 'Hardware store',
      reliability_positive: 20,
      reliability_negative: 4,
      rating: 88,
      suburb: 'Grey Lynn',
      city: 'Auckland',
    },
    {
      id: 3,
      auth0_ID: '3',
      name: 'Eye Pop',
      address: '4 Vision St, Grey Lynn, Auckland',
      category: 'Optometrist',
      reliability_positive: 34,
      reliability_negative: 7,
      rating: 90,
      suburb: 'Grey Lynn',
      city: 'Auckland',
    },
    {
      id: 4,
      auth0_ID: '4',
      name: 'Coffee Candy',
      address: '10 Espresso St, Grey Lynn, Auckland',
      category: 'Cafe',
      reliability_positive: 34,
      reliability_negative: 43,
      rating: 98,
      suburb: 'Grey Lynn',
      city: 'Auckland',
    },
    {
      id: 5,
      auth0_ID: '5',
      name: "Delilah's Dentist",
      address: '50 Filling St, Grey Lynn, Auckland',
      category: 'Dentist',
      reliability_positive: 45,
      reliability_negative: 7,
      rating: 50,
      suburb: 'Grey Lynn',
      city: 'Auckland',
    },
    {
      id: 6,
      auth0_ID: '6',
      name: 'Espresso Myself',
      address: '80 Loud St, Grey Lynn, Auckland',
      category: 'Cafe',
      reliability_positive: 43,
      reliability_negative: 6,
      rating: 67,
      suburb: 'Grey Lynn',
      city: 'Auckland',
    },
    {
      id: 7,
      auth0_ID: '7',
      name: 'So Tasty',
      address: '43 Rangiatea Rd, Ponsonby, Auckland',
      category: 'Cafe',
      reliability_positive: 4,
      reliability_negative: 5,
      rating: 85,
      suburb: 'Ponsonby',
      city: 'Auckland',
    },
    {
      id: 8,
      auth0_ID: '8',
      name: "Bob's Supplies",
      address: '70 Hammer St, Ponsonby, Auckland',
      category: 'Hardware store',
      reliability_positive: 23,
      reliability_negative: 6,
      rating: 89,
      suburb: 'Ponsonby',
      city: 'Auckland',
    },
    {
      id: 9,
      auth0_ID: '9',
      name: 'Look See',
      address: '4 Ojo St, Ponsonby, Auckland',
      category: 'Optometrist',
      reliability_positive: 74,
      reliability_negative: 3,
      rating: 98,
      suburb: 'Ponsonby',
      city: 'Auckland',
    },
    {
      id: 10,
      auth0_ID: '10',
      name: 'Energize',
      address: '12 Kiwi St, Ponsonby, Auckland',
      category: 'Cafe',
      reliability_positive: 54,
      reliability_negative: 23,
      rating: 91,
      suburb: 'Ponsonby',
      city: 'Auckland',
    },
    {
      id: 11,
      auth0_ID: '11',
      name: 'Waititi Family Dentist',
      address: '54 Yazi St, Ponsonby, Auckland',
      category: 'Dentist',
      reliability_positive: 45,
      reliability_negative: 7,
      rating: 50,
      suburb: 'Ponsonby',
      city: 'Auckland',
    },
    {
      id: 12,
      auth0_ID: '12',
      name: 'Deux Amis Cafe',
      address: '80 Quentin St, Ponsonby, Auckland',
      category: 'Cafe',
      reliability_positive: 43,
      reliability_negative: 6,
      rating: 67,
      suburb: 'Ponsonby',
      city: 'Auckland',
    },
    {
      id: 13,
      auth0_ID: '13',
      name: "Anastasia's Hairdressing",
      address: '23 Cabello Rd, Devonport, Auckland',
      category: 'Hairdressers',
      reliability_positive: 4,
      reliability_negative: 5,
      rating: 80,
      suburb: 'Devonport',
      city: 'Auckland',
    },
    {
      id: 14,
      auth0_ID: '14',
      name: 'Tool Team',
      address: '70 Aroha St, Devonport, Auckland',
      category: 'Hardware store',
      reliability_positive: 20,
      reliability_negative: 4,
      rating: 88,
      suburb: 'Devonport',
      city: 'Auckland',
    },
    {
      id: 15,
      auth0_ID: '15',
      name: '2022 Vision',
      address: '4 Vista St, Devonport, Auckland',
      category: 'Optometrist',
      reliability_positive: 34,
      reliability_negative: 7,
      rating: 90,
      suburb: 'Devonport',
      city: 'Auckland',
    },
    {
      id: 16,
      auth0_ID: '16',
      name: 'Kind Coffee',
      address: '10 Aroma St, Devonport, Auckland',
      category: 'Cafe',
      reliability_positive: 34,
      reliability_negative: 43,
      rating: 98,
      suburb: 'Devonport',
      city: 'Auckland',
    },
    {
      id: 17,
      auth0_ID: '17',
      name: 'Shiny and Bright',
      address: '50 Diente St, Devonport, Auckland',
      category: 'Dentist',
      reliability_positive: 45,
      reliability_negative: 7,
      rating: 50,
      suburb: 'Devonport',
      city: 'Auckland',
    },
    {
      id: 18,
      auth0_ID: '18',
      name: 'Delicious',
      address: '80 Haochi St, Devonport, Auckland',
      category: 'Cafe',
      reliability_positive: 43,
      reliability_negative: 6,
      rating: 67,
      suburb: 'Devonport',
      city: 'Auckland',
    },
    {
      id: 19,
      auth0_ID: '19',
      name: 'Cold Brew Palace',
      address: '43 Tui Rd, Manukau, Auckland',
      category: 'Cafe',
      reliability_positive: 4,
      reliability_negative: 5,
      rating: 85,
      suburb: 'Manukau',
      city: 'Auckland',
    },
    {
      id: 20,
      auth0_ID: '20',
      name: 'Build Better',
      address: '70 Main St, Manukau, Auckland',
      category: 'Hardware store',
      reliability_positive: 23,
      reliability_negative: 6,
      rating: 89,
      suburb: 'Manukau',
      city: 'Auckland',
    },
    {
      id: 21,
      auth0_ID: '21',
      name: "Heilala's Optometry",
      address: '4 Yanjing St, Manukau, Auckland',
      category: 'Optometrist',
      reliability_positive: 74,
      reliability_negative: 3,
      rating: 98,
      suburb: 'Manukau',
      city: 'Auckland',
    },
    {
      id: 22,
      auth0_ID: '22',
      name: 'Creative Kai',
      address: '12 Kiwi St, Grey Lynn, Auckland',
      category: 'Cafe',
      reliability_positive: 54,
      reliability_negative: 3,
      rating: 91,
      suburb: 'Grey Lynn',
      city: 'Auckland',
    },
    {
      id: 23,
      auth0_ID: '23',
      name: 'Healthy Teeth',
      address: '54 Shine St, Manukau, Auckland',
      category: 'Dentist',
      reliability_positive: 55,
      reliability_negative: 4,
      rating: 70,
      suburb: 'Manukau',
      city: 'Auckland',
    },
    {
      id: 24,
      auth0_ID: '24',
      name: 'Kaffeehaus',
      address: '80 Kapu St, Manukau, Auckland',
      category: 'Cafe',
      reliability_positive: 43,
      reliability_negative: 6,
      rating: 67,
      suburb: 'Manukau',
      city: 'Auckland',
    },
    {
      id: 25,
      auth0_ID: '25',
      name: 'Hairdressing Heaven',
      address: '133 Tress Rd, Grey Lynn, Auckland',
      category: 'Hairdressers',
      reliability_positive: 50,
      reliability_negative: 5,
      rating: 84,
      suburb: 'Grey Lynn',
      city: 'Auckland',
    },
    {
      id: 26,
      auth0_ID: '26',
      name: 'Hip Hair',
      address: '223 Locks Rd, Ponsonby, Auckland',
      category: 'Hairdressers',
      reliability_positive: 4,
      reliability_negative: 39,
      rating: 40,
      suburb: 'Ponsonby',
      city: 'Auckland',
    },
    {
      id: 27,
      auth0_ID: '27',
      name: 'Hair Razing',
      address: '123 Volos Rd, Manukau, Auckland',
      category: 'Hairdressers',
      reliability_positive: 4,
      reliability_negative: 5,
      rating: 90,
      suburb: 'Manukau',
      city: 'Auckland',
    },
    {
      id: 28,
      auth0_ID: '28',
      name: 'Angles',
      address: '13 Mane Rd, Devonport, Auckland',
      category: 'Hairdressers',
      reliability_positive: 76,
      reliability_negative: 28,
      rating: 71,
      suburb: 'Devonport',
      city: 'Auckland',
    },
  ])
}
