/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('safetyCriteria').del()
  await knex('safetyCriteria').insert([
    {
      id: 1,
      business_id: '1',
      ventilation: 0,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 0,
      masking: 0,
    },
    {
      id: 2,
      business_id: '2',
      ventilation: 1,
      vaccinePass: 1,
      vaccineStaff: 0,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 2,
    },
    {
      id: 3,
      business_id: '3',
      ventilation: 1,
      vaccinePass: 0,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 4,
      business_id: '4',
      ventilation: 1,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 0,
      minSpacing: 1,
      masking: 2,
    },
    {
      id: 5,
      business_id: '5',
      ventilation: 2,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 6,
      business_id: '6',
      ventilation: 0,
      vaccinePass: 0,
      vaccineStaff: 0,
      handSanitizer: 0,
      cleaningProtocol: 0,
      minSpacing: 0,
      masking: 0,
    },
    {
      id: 7,
      business_id: '7',
      ventilation: 0,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 0,
      masking: 0,
    },
    {
      id: 8,
      business_id: '8',
      ventilation: 1,
      vaccinePass: 1,
      vaccineStaff: 0,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 2,
    },
    {
      id: 9,
      business_id: '9',
      ventilation: 1,
      vaccinePass: 0,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 10,
      business_id: '10',
      ventilation: 1,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 0,
      minSpacing: 1,
      masking: 2,
    },
    {
      id: 11,
      business_id: '11',
      ventilation: 2,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 12,
      business_id: '12',
      ventilation: 0,
      vaccinePass: 0,
      vaccineStaff: 0,
      handSanitizer: 0,
      cleaningProtocol: 0,
      minSpacing: 0,
      masking: 0,
    },
    {
      id: 13,
      business_id: '13',
      ventilation: 0,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 0,
      masking: 0,
    },
    {
      id: 14,
      business_id: '14',
      ventilation: 1,
      vaccinePass: 1,
      vaccineStaff: 0,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 2,
    },
    {
      id: 15,
      business_id: '15',
      ventilation: 1,
      vaccinePass: 0,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 16,
      business_id: '16',
      ventilation: 1,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 0,
      minSpacing: 1,
      masking: 2,
    },
    {
      id: 17,
      business_id: '17',
      ventilation: 2,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 18,
      business_id: '18',
      ventilation: 0,
      vaccinePass: 0,
      vaccineStaff: 0,
      handSanitizer: 0,
      cleaningProtocol: 0,
      minSpacing: 0,
      masking: 0,
    },
    {
      id: 19,
      business_id: '19',
      ventilation: 0,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 0,
      masking: 0,
    },
    {
      id: 20,
      business_id: '20',
      ventilation: 1,
      vaccinePass: 1,
      vaccineStaff: 0,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 2,
    },
    {
      id: 21,
      business_id: '21',
      ventilation: 1,
      vaccinePass: 0,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 22,
      business_id: '22',
      ventilation: 1,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 0,
      minSpacing: 1,
      masking: 2,
    },
    {
      id: 23,
      business_id: '23',
      ventilation: 2,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 24,
      business_id: '24',
      ventilation: 0,
      vaccinePass: 0,
      vaccineStaff: 0,
      handSanitizer: 0,
      cleaningProtocol: 0,
      minSpacing: 0,
      masking: 0,
    },
    {
      id: 25,
      business_id: '25',
      ventilation: 1,
      vaccinePass: 0,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 26,
      business_id: '26',
      ventilation: 1,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 0,
      minSpacing: 1,
      masking: 2,
    },
    {
      id: 27,
      business_id: '27',
      ventilation: 2,
      vaccinePass: 1,
      vaccineStaff: 1,
      handSanitizer: 1,
      cleaningProtocol: 1,
      minSpacing: 2,
      masking: 4,
    },
    {
      id: 28,
      business_id: '28',
      ventilation: 0,
      vaccinePass: 0,
      vaccineStaff: 0,
      handSanitizer: 0,
      cleaningProtocol: 0,
      minSpacing: 0,
      masking: 0,
    },
  ])
}
